# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               My Cluster
tagline:             'A FYP project'
description:         'Theme by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yao Yang
  url:               https://www.linkedin.com/in/yao-yang-leow-2b8b77117/
  email:             leowyaoyang@gmail.com

# Custom vars
version:             1.0.0
