# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Welcome to My Cluster
tagline:             'FYP 2018'
description:         'This blog is dedicated to my Final Year Project entitled "An experimental study of graph neural networks."
 under the supervision of <a href= "http://www.ntu.edu.sg/home/xbresson/">Prof. Xavier Bresson</a>.'. 
 All blog posts are authored by <a href= "https://www.linkedin.com/in/yao-yang-leow-2b8b77117/">Leow Yao Yang</a>.
url:                 https://signapoop.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yao Yang
  url:               https://www.linkedin.com/in/yao-yang-leow-2b8b77117/
  email:             leowyaoyang@gmail.com

# Custom vars
version:             1.0.0
