# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Welcome to My Cluster
tagline:             'A Final Year Project'
description:         'An experimental study of graph neural networks <br>
Posts authored by: <a href= "https://www.linkedin.com/in/yao-yang-leow-2b8b77117/">Leow Yao Yang</a> <br>
Supervised by: <a href= "http://www.ntu.edu.sg/home/xbresson/">Prof. Xavier Bresson</a>.'
url:                 https://signapoop.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yao Yang
  url:               https://www.linkedin.com/in/yao-yang-leow-2b8b77117/
  email:             leowyaoyang@gmail.com

# Custom vars
version:             1.0.0
