# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           "/:title"

# Setup
title:               A Geometric Progression
tagline:             'Leow Yao Yang'
description:         'This blog is dedicated to the ICLR 2019 Workshop Paper, "GraphTSNE: A Visualization Technique for Graph-Structured Data".
 This research was performed under the supervision of <a href= "http://www.ntu.edu.sg/home/xbresson/">Prof. Xavier Bresson</a>.
 All blog posts are authored by <a href= "https://www.linkedin.com/in/yao-yang-leow-2b8b77117/">Leow Yao Yang</a>.'
url:                 https://signapoop.github.io/
baseurl:             ''
paginate:            1

defaults:
 -
   scope:
     path: "_slides"  #__
   values:
     layout: "iframe"

collections:
 slides:
   output: true

# About/contact
author:
  name:              Yao Yang
  url:               https://www.linkedin.com/in/yao-yang-leow-2b8b77117/
  email:             leowyaoyang@gmail.com

# Custom vars
version:             1.0.0
